"""Adapters for the released upstream applications used by AWDP.

The adapter has no challenge logic and no fixture responses.  It reads the
small public manifest generated by ``integrations/upstream/bootstrap.sh`` and
probes each real application before DVLAA redirects a learner to it.  Keeping
this boundary separate makes it impossible for the console to accidentally
turn an unavailable upstream into a fake success page.
"""

from __future__ import annotations

import json
import os
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from ..paths import PROJECT_ROOT


UPSTREAM_IDS = frozenset({3, 4, 5, 7, 9, 10})
DEFAULT_STATE_FILE = PROJECT_ROOT / "integrations" / "upstream" / "runtime" / "targets.json"
DEFAULT_TARGETS: dict[int, dict[str, str]] = {
    3: {"project": "RAGFlow", "version": "v0.14.1", "public_url": "http://127.0.0.1:6303", "health_path": "/v1/system/status"},
    4: {"project": "Langflow", "version": "1.0.18", "public_url": "http://127.0.0.1:7864", "health_path": "/health"},
    5: {"project": "Flowise", "version": "1.8.2", "public_url": "http://127.0.0.1:3005", "health_path": "/api/v1/ping"},
    7: {"project": "Open WebUI", "version": "v0.1.116", "public_url": "http://127.0.0.1:8087", "health_path": "/health"},
    9: {"project": "RAGFlow", "version": "v0.14.1", "public_url": "http://127.0.0.1:6309", "health_path": "/v1/system/status"},
    10: {"project": "n8n", "version": "1.99.0", "public_url": "http://awdp10.localhost:5080", "health_path": "/healthz"},
}
_PROBE_TTL = 2.0
_probe_cache: dict[str, tuple[float, bool]] = {}
_probe_lock = threading.Lock()


def state_path() -> Path:
    return Path(os.environ.get("DVLAA_UPSTREAM_STATE_FILE", str(DEFAULT_STATE_FILE))).expanduser()


def _load_manifest() -> dict[str, Any]:
    try:
        value = json.loads(state_path().read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return {}
    return value if isinstance(value, dict) else {}


def _target(challenge_id: int) -> dict[str, str]:
    challenge_id = int(challenge_id)
    fallback = dict(DEFAULT_TARGETS.get(challenge_id, {}))
    manifest = _load_manifest().get("targets", {})
    item = manifest.get(f"{challenge_id:02d}", {}) if isinstance(manifest, dict) else {}
    if isinstance(item, dict):
        for key in ("project", "version", "public_url", "health_path"):
            if str(item.get(key) or "").strip():
                fallback[key] = str(item[key]).strip()
    # The DVLAA container reaches host services by this address while the
    # browser keeps using the public URL from the generated manifest.
    internal = os.environ.get(f"DVLAA_UPSTREAM_URL_{challenge_id:02d}", "").strip()
    if internal:
        fallback["probe_url"] = internal.rstrip("/")
    else:
        fallback["probe_url"] = fallback.get("public_url", "").rstrip("/")
    public = os.environ.get(f"DVLAA_UPSTREAM_PUBLIC_URL_{challenge_id:02d}", "").strip()
    if public:
        fallback["public_url"] = public.rstrip("/")
    return fallback


def _probe_url(item: dict[str, str]) -> str:
    return f"{item.get('probe_url', '').rstrip('/')}{item.get('health_path', '/') or '/'}"


def reachable(challenge_id: int) -> bool:
    if int(challenge_id) not in UPSTREAM_IDS:
        return False
    item = _target(challenge_id)
    url = _probe_url(item)
    if not url.startswith(("http://", "https://")):
        return False
    now = time.monotonic()
    with _probe_lock:
        cached = _probe_cache.get(url)
        if cached and now - cached[0] < _PROBE_TTL:
            return cached[1]
    request = urllib.request.Request(url, headers={"Accept": "application/json,text/html;q=0.9"})
    try:
        with urllib.request.urlopen(request, timeout=1.8) as response:
            ok = 200 <= int(response.status) < 500
    except urllib.error.HTTPError as exc:
        # A login page or a protected health endpoint still proves that the
        # actual upstream HTTP server is alive.
        ok = 400 <= int(exc.code) < 500
    except (OSError, TimeoutError, ValueError):
        ok = False
    with _probe_lock:
        _probe_cache[url] = (time.monotonic(), ok)
    return ok


def native_state(challenge_id: int) -> dict[str, Any]:
    challenge_id = int(challenge_id)
    item = _target(challenge_id)
    configured = challenge_id in UPSTREAM_IDS and bool(item.get("public_url"))
    live = reachable(challenge_id) if configured else False
    mode = os.environ.get("DVLAA_UPSTREAM_MODE", "auto").strip().lower()
    if mode not in {"auto", "native", "disabled"}:
        mode = "auto"
    enabled = mode == "native" or (mode == "auto" and configured and live)
    return {
        "challenge_id": challenge_id,
        "mode": mode,
        "enabled": enabled,
        "configured": configured,
        "reachable": live,
        "project": item.get("project", ""),
        "upstream_project": item.get("project", ""),
        "upstream_version": item.get("version", ""),
        "base_url": item.get("public_url", "") if enabled else "",
        "target_url": item.get("public_url", "") if enabled else "",
        "health_path": item.get("health_path", ""),
        "service_version": "upstream-compose-1",
    }


def native_target_url(challenge_id: int) -> str | None:
    status = native_state(challenge_id)
    value = str(status.get("target_url") or "").strip()
    return value if status.get("enabled") and value else None


def status() -> dict[str, Any]:
    targets = {str(cid): native_state(cid) for cid in sorted(UPSTREAM_IDS)}
    return {"mode": os.environ.get("DVLAA_UPSTREAM_MODE", "auto"), "targets": targets, "enabled": any(item.get("enabled") for item in targets.values())}


def reset_probe_cache() -> None:
    with _probe_lock:
        _probe_cache.clear()


__all__ = ["UPSTREAM_IDS", "native_state", "native_target_url", "reachable", "reset_probe_cache", "state_path", "status"]
